name = "NPFinancial"
uuid = "d92e12fc-aea5-418c-9372-8108a4db1700"
authors = ["Tom Kwong <tk3369@gmail.com>"]
version = "0.3.2"

[deps]
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"

[compat]
Polynomials = "0.6, 0.7, 0.8, 1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
